global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8000"]
  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:8000"]
  - job_name: catalog-service
    metrics_path: /metrics
    static_configs:
      - targets: ["catalog-service:8000"]
  - job_name: search-service
    metrics_path: /metrics
    static_configs:
      - targets: ["search-service:8000"]
  - job_name: download-service
    metrics_path: /metrics
    static_configs:
      - targets: ["download-service:8000"]
  - job_name: stream-service
    metrics_path: /metrics
    static_configs:
      - targets: ["stream-service:8000"]
  - job_name: admin-service
    metrics_path: /metrics
    static_configs:
      - targets: ["admin-service:8000"]
